# Generated by Django 4.1.6 on 2023-07-15 19:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('id_carro', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_carro', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('ano_fabricacao', models.IntegerField(max_length=4)),
                ('ano_modelo', models.IntegerField(max_length=4)),
                ('cor', models.CharField(max_length=30)),
                ('tipo_combustivel', models.CharField(max_length=10)),
                ('cambio', models.CharField(max_length=10)),
                ('foto', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
