# Generated by Django 4.1.6 on 2023-07-15 20:17

import carros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0002_alter_carros_ano_fabricacao_alter_carros_ano_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carros',
            name='foto',
            field=models.ImageField(upload_to=carros.models.upload_imagem_carro),
        ),
    ]
