# Generated by Django 4.1.6 on 2023-07-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0004_carros_quilometragem'),
    ]

    operations = [
        migrations.AddField(
            model_name='carros',
            name='valor',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
