# Generated by Django 4.1.6 on 2023-07-20 17:45

import carros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0005_carros_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carros',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=carros.models.upload_imagem_carro),
        ),
    ]
