# Generated by Django 4.2.7 on 2024-01-31 15:48

import carros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0006_alter_carros_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carros',
            name='foto',
            field=models.ImageField(null=True, upload_to=carros.models.upload_imagem_carro),
        ),
    ]
