# Generated by Django 5.2.17 on 2026-09-29 17:28

import carros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0007_alter_carros_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carros',
            options={'ordering': ['valor'], 'verbose_name': 'carro', 'verbose_name_plural': 'carros'},
        ),
        migrations.AlterField(
            model_name='carros',
            name='ano_fabricacao',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='carros',
            name='ano_modelo',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='carros',
            name='cambio',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatico', 'Automático')], max_length=10),
        ),
        migrations.AlterField(
            model_name='carros',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=carros.models.upload_imagem_carro),
        ),
        migrations.AlterField(
            model_name='carros',
            name='quilometragem',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='carros',
            name='tipo_combustivel',
            field=models.CharField(choices=[('gasolina', 'Gasolina'), ('alcool', 'Álcool'), ('flex', 'Flex'), ('diesel', 'Diesel'), ('gas-natural', 'Gás Natural'), ('eletrico', 'Elétrico'), ('hibrido', 'Híbrido')], max_length=20),
        ),
        migrations.AlterField(
            model_name='carros',
            name='valor',
            field=models.PositiveIntegerField(),
        ),
    ]
